### PR TITLE
add sampler scheduling to notebook

### PR DESCRIPTION
**Pull request by Kitchenn3**
this adds the ability to optionally schedule samplers, ddim and plms will be added at a later date.

### CODE REVIEW

**Comment by Kitchenn3** [comment]
added update to set default value of enable_schedule_samplers to False

**Comment by Kitchenn3** [comment]
let me know If I need to make this PR into :dev instead. I opened one, but the branch seemed out of date compared to main.

**Comment by deforum** [comment]
oh i noticed you are not passing the sampler to the generate function through args

**Comment by deforum** [comment]
oops

**Comment by Kitchenn3** [comment]
thats probably why it works so well

**Comment by Kitchenn3** [comment]
im sorry, what do you mean though? in render.py the sampler name is being passed to generate(sampler_name). 

I may be mistaken if you are referring to the generate methods within
render_interpolation(args, anim_args, animation_prompts, root): in render.py.

from my understanding that worked similar to flowframes. Is that something that samplers are required for?

**Comment by deforum** [comment]
yeah added this to dev, but it makes no sense to pass the sampler name to generate to just put it in args - this should happen before so the generate inputs dont change

**Pull request closed without merging**
